name: ikpsk1-lib-test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "common/**/*.ts"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"

      - name: Install dependencies
        run: |
          ./dev-init.sh

      - name: Check formatting
        run: |
          npx prettier --write --ignore-unknown

      - name: Run tests
        run: |
          cd common
          npm run test
